version: "3.8"
services:
  frontend:
    build: ./client
    container_name: frontend_c
    ports:
      - '4173:4173'
  backend:
    build: ./server
    container_name: backend_c
    ports:
      - '8080:8080'
    stdin_open: true
    tty: true